version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'mercaonline'
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: 'no'

  redis:
    container_name: redis
    image: 'redis:latest'
    command: redis-server --requirepass password
    ports:
      - '6379:6379'

  haproxy-web: 
    container_name: haproxy-web
    image: 'haproxy:2.1'
    ports:
      - '81:80'
      - '443:443'
      - '8404:8404'
    volumes:
      - /etc/haproxy:/usr/local/etc/haproxy:ro
      #- ./volumes/haproxy-web:/usr/local/etc/haproxy:ro
    depends_on:
      - mercaonline-web-1
      - mercaonline-web-2

  mercaonline-web-1:
    ports:
      - "8443:8443"
    container_name: mercaonline-web-1 
    image: 'mercaonline-web:v2'
    depends_on:
       - mysql
       - redis
  mercaonline-web-2:
    ports:
      - "8080:8443"
    container_name: mercaonline-web-2
    image: 'mercaonline-web:v2'
    depends_on:
      - mysql
      - redis
  mercaonline-SI-1:
     ports:
      - "9999:9999"
     container_name: mercaonline-SI-1
     image: 'mercaonline-servinterno:v3'
     depends_on:
      - mercaonline-web-1
      - mercaonline-web-2
  haproxy-SI:
    container_name: haproxy-SI
    image: 'haproxy:2.1'
    ports:
      - '8405:8404'
    volumes:
      - /home/ismaelmdf:/usr/local/etc/haproxy:ro
    depends_on:
      - mercaonline-SI-1

     
     
     
     
     
     
     